export const tinyCssClasses = {
    /* ===========Positioning & utils========= */
    /* display */
    dyFlex: "d-flex",
    dGrid: "d-grid",
    dBlock: "d-block",
    /* justify content */
    jcCenter: "jc-center",
    jcStart: "jc-start",
    jcEnd: "jc-end",
    jcAround: "jc-around",
    jcBetween: "jc-between",
    jcEvenly: "jc-evenly",
    jcStretch: "jc-stretch",
    jcBaseline: "jc-baseline",
    /* justify self */
    jsCenter: "js-center",
    jsStart: "js-start",
    jsEnd: "js-end",
    jsStretch: "js-stretch",
    jsBaseline: "js-baseline",
    // align item
    aiCenter: "ai-center",
    aiStart: "ai-start",
    aiEnd: "ai-end",
    aiStretch: "ai-stretch",
    aiBasLine: "ai-baseline",
    // align self
    asCenter: "as-center",
    asStart: "as-start",
    asEnd: "as-end",
    asStretch: "as-stretch",
    asBasLine: "as-baseline",
    // align content
    acCenter: "ac-center",
    acStart: "ac-start",
    acEnd: "ac-end",
    acAround: "ac-around",
    acBetween: "ac-between",
    acEvenly: "ac-evenly",
    // flex direction
    flexColumn: "flex-column",
    flexRow: "flex-row",
    flexColumnReverse: "flex-column-reverse",
    flexRowReverse: "flex-row-reverse",
    // flex wrap, shrink, grow
    flexWrap: "flex-wrap",
    flexNoWrap: "flex-no-wrap",
    flexShrink: "flex-shrink",
    flexNoShrink: "flex-no-shrink",
    flexGrow: "flex-grow",
    flexNoGrow: "flex-no-grow",
    // float
    floatLeft: "float-left",
    floatRight: "float-right",
    floatNone: "float-none",
    // position
    pAbsolute: "p-absolute",
    pRelative: "p-relative",
    pFixed: "p-fixed",
    pSticky: "p-sticky",
    pStatic: "p-static",
    // cursor
    cPointer: "c-pointer",
    cNotAllowed: "c-not-allowed",
    cGrab: 'c-grab',
    cProgress: 'c-progress',
    // list style
    listNone: "list-none",
    listSquare: "list-square",
    listCircle: "list-circle",
    listDisc: "list-disc",
    // text decoration
    textDashed: "text-dashed",
    textDotted: "text-dotted",
    textDouble: "text-double",
    textLineThrough: "text-line-through",
    textNone: "text-none",
    textSolid: "text-solid",
    textUnderline: "text-underline",
    textWavy: "text-wavy",

    /* =========Components=========== */
    // button
    btn: "btn", 
    btnPrimary: "btn-primary",
    btnSecondary: "btn-secondary",
    btnSuccess: "btn-success", 
    btnDanger: "btn-danger",
    btnChill: "btn-chill",
    btnClose: "btn-close",
    btnBlock: "btn-block",
    // lists
    ul:"ul",
    ol:"ol",
    ulWithBg:"ul-with-bg",
    olWithBg:"ol-with-bg",
    // table
    table: "table",
    thead: "thead",
    tbody: "tbody",
    tfoot: "tfoot",
    tr: "tr",
    td: "td",
    th: "th",
    tdPrimary: "td-primary",
    thPrimary: "th-primary",
    tdSecondary: "td-secondary",
    thSecondary: "th-secondary",
    tdSuccess: "td-success",
    thSuccess: "th-success",
    tdDanger: "td-danger",
    thDanger: "th-danger",
}